name: Generate and push Documentation

on:
  push:
    branches: [ "main", "manual" ]
  pull_request:
    branches: [ "main", "manual"  ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages.
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  generate_doc:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie

    steps:
    - name: Install package dependencies.
      run: |
        apt-get update
        apt-get install -y \
          bison \
          clang \
          cmake \
          flex \
          gcc \
          git \
          libbacktrace-dev \
          libcairo2-dev \
          libncurses-dev \
          libwlroots-0.18-dev \
          pkg-config \
          plantuml \
          xwayland

    - name: Checkout code, including git submodules.
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Configure wlmaker through CMake, with doxygen.
      run: |
        cmake -Dconfig_DOXYGEN_CRITICAL=ON -B build/

    - name: Build documentation.
      run: cmake --build build/ --target doc

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        build_path: build/doc/html
