name: Generate and publish Documentation

on:
  # The principal run is on pushes targeting the default branch.
  push:
    branches: [ "main" ]
  # We also run on pull requests towards main, to catch issues with generating
  # the documentation before they're merged.
  pull_request:
    branches: [ "main"  ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run
# in-progress and latest queued. However, do NOT cancel in-progress runs as we
# want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  INSTALL_PATH: "${HOME}/wlmaker"
  INSTALL_LIBRARY_PATH: "${HOME}/wlmaker/lib/$(dpkg-architecture -qDEB_HOST_MULTIARCH)"
  INSTALL_PKGCONFIG_PATH: "${HOME}/wlmaker/lib/$(dpkg-architecture -qDEB_HOST_MULTIARCH)/pkgconfig/:${HOME}/wlmaker/share/pkgconfig/"

jobs:
  # Generate documentation, in a container.
  generate_doc:
    name: "Generate documentation"
    runs-on: ubuntu-latest
    container:
      image: debian:trixie

    steps:
      - name: Install package dependencies.
        run: |
          apt-get update
          apt-get install -y \
            bison \
            clang \
            cmake \
            doxygen \
            flex \
            gcc \
            git \
            hwdata \
            libbacktrace-dev \
            libcairo2-dev \
            libdisplay-info-dev \
            libdrm-dev \
            libinput-dev \
            libpixman-1-dev \
            libseat-dev \
            libudev-dev \
            libwayland-dev \
            libxcb-composite0-dev \
            libxcb-dri3-dev \
            libxcb-ewmh-dev \
            libxcb-icccm4-dev \
            libxcb-present-dev \
            libxcb-render-util0-dev \
            libxcb-res0-dev \
            libxcb-shm0-dev \
            libxcb-xinput-dev \
            libxcb-xkb-dev \
            libxcb1-dev \
            libxdg-basedir-dev \
            libxkbcommon-dev \
            meson \
            pkgconf \
            plantuml \
            seatd \
            wayland-protocols \
            xmlto \
            xsltproc

      - name: Checkout code, including git submodules.
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure and build dependencies/.
        run: |
          export CC="${{ matrix.compiler }}"
          export PKG_CONFIG_PATH="${{ env.INSTALL_PKGCONFIG_PATH }}"
          export LD_LIBRARY_PATH="${{ env.INSTALL_LIBRARY_PATH }}"
          export PATH="${PATH}:${{ env.INSTALL_PATH }}/bin"
          cmake -DCMAKE_INSTALL_PREFIX:PATH=${{ env.INSTALL_PATH }} dependencies/ -B dependencies/build/
          cmake --build dependencies/build

      - name: Configure wlmaker through CMake, with doxygen.
        run: |
          export PKG_CONFIG_PATH="${{ env.INSTALL_PKGCONFIG_PATH }}"
          export LD_LIBRARY_PATH="${{ env.INSTALL_LIBRARY_PATH }}"
          export PATH="${PATH}:${{ env.INSTALL_PATH }}/bin"
          cmake -Dconfig_DOXYGEN_CRITICAL=ON -B build/

      - name: Build documentation.
        run: |
          export PKG_CONFIG_PATH="${{ env.INSTALL_PKGCONFIG_PATH }}"
          export LD_LIBRARY_PATH="${{ env.INSTALL_LIBRARY_PATH }}"
          export PATH="${PATH}:${{ env.INSTALL_PATH }}/bin"
          cmake --build build/ --target doc

      - name: Configure GitHub Pages.
        uses: actions/configure-pages@v5

      - name: Upload the generated documentation.
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'build/doc/html/'

  # Deploys the uploaded documentation to GitHub Pages.
  deploy:
    name: "Deploy the generated documentation"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: generate_doc
    # Skip deployment unless it's the "push" on "main".
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Deploy to GitHub Pages.
        id: deployment
        uses: actions/deploy-pages@v4
